auto: true

markdown: rdiscount
pygments: true
paginate: 10
permalink: /:title

title: demonkit.gitgub.io
url: http://demonkit.github.io
author_info: <a href="http://demonkit.github.io/">demonkit</a>
